export default {
  type: 'warning-table-list',
  title: '告警管理',
  subTitle: 'Abnormal alarm',
  speed: 12,
  isScroll: true,
  intervalDelay: 5000,
  isVirtual: '0',
  instance: [],
  timeSpan: 1,
  style: {
    width: '480',
    height: '367',
    backgroundColor: 'rgba(39, 45, 54, 1)',
    borderBottomLeftRadius: '8px',
    borderBottomRightRadius: '8px',
    borderTopLeftRadius: '8px',
    borderTopRightRadius: '8px',
  },
};
