export default {
  type: 'dynamic-monitoring',
  visibleNumber: 5,
  title: '运行工况',
  style: {
    width: '117',
    height: '80',
    color: 'rgba(255, 255, 255, 1)',
    backgroundColor: 'rgba(0,163,255,0.06)',
    borderTopStyle: 'solid',
    borderTopColor: '#0A283A',
    borderTopWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: '#0A283A',
    borderRightWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#0A283A',
    borderBottomWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: '#0A283A',
    borderLeftWidth: '1px',
  },
};
