packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # edoms-designer in direct subdirs of edoms-designer/
  - 'edoms-designer'
  # exclude packages that are inside test directories
  - '!**/test/**'
