export default {
  style: {
    visibility: 'visible',
    width: '56px',
    height: '30px',
    padding: '2px',
    color: '#ffffff',
    backgroundColor: '#1D4B77',
    borderTopStyle: 'solid',
    borderTopColor: '#ffffff',
    borderTopWidth: '1px',
    borderTopLeftRadius: '3px',
    borderTopRightRadius: '3px',
    borderRightStyle: 'solid',
    borderRightColor: '#ffffff',
    borderRightWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#ffffff',
    borderBottomWidth: '1px',
    borderBottomLeftRadius: '3px',
    borderBottomRightRadius: '3px',
    borderLeftStyle: 'solid',
    borderLeftColor: '#ffffff',
    borderLeftWidth: '1px',
  },
};
